### ISSUE TITLE
Remove repetition from tests

### ISSUE THREAD

**Issue by pivovarit** [pivovarit/parallel-collectors#149]
Currently, most tests are super repetitive copy-pastes of each other.

All because of the time and pain related to working with Java generics... but I still believe this can be simplified to avoid all this form of copy-pastes.

**Comment by RobPiwowarek** [comment]
on it

**Comment by pivovarit** [comment]
Done as much as possible, further refactorings lead to monsters like:
```
private static DynamicTest shouldCollectWithMappingAndNotSwallowExceptionUnbounded(TriFunction<Function<Integer, Integer>, Executor, Integer, Collector<Integer, List<CompletableFuture<Integer>>, ? extends CompletableFuture<? extends Collection<Integer>>>> collector, String name
```
