### ISSUE TITLE
Please avoid suggesting parallel N+1 database interaction patterns

### ISSUE THREAD

**Issue by lukaseder** [pivovarit/parallel-collectors#166]
The current readme suggests this example here:

```java
list.stream()
  .collect(parallelToList(i -> fetchFromDb(i), executor, 2)).orTimeout(1000, MILLISECONDS)
  .thenAccept(System.out::println)
  .thenRun(() -> System.out.println("Finished!"));
```

And it reiterates on the example later on. Please do not suggest fetching individual values from the database one by one, by ID, especially when an ID *set* is available, which there obviously is, in the presence of such an ID list / stream.

A lot of junior developers will think "hey we can speed up our app by distributing our trivial query across several threads". The result is saturated threads both on the client and in the database, when batch and/or bulk SQL operations would have been much better for both systems.

As API / tool vendors, it is our responsibility to show simple examples that do not misguide junior developers into thinking that a quick fix will really solve their problems.

**Comment by pivovarit** [comment]
Yes, it's a very good suggestion :) the example was supposed to be trivial and abstract but might promote bad practices. Will definitely implement shortly!

**Comment by pivovarit** [comment]
Generally, it's not about N + 1 exclusively. Whenever you need to parallelize something, make sure this is actually needed. Will add notes

**Comment by lukaseder** [comment]
Absolutely agree!

**Comment by pivovarit** [comment]
I think we can close it for now, I will keep improving the docs while keeping that in mind as well!
