### ISSUE TITLE
MavenGate (CVE)

### ISSUE THREAD

**Issue by amareshdlphx** [pivovarit/parallel-collectors#846]
XFrog triggers an alert on package: com.pivovarit:parallel-collectors

Looks like com.pivovarit is not registered hence groupId can be claimed by malicious user

**Comment by pivovarit** [comment]
Thanks for spotting that, I just reclaimed it :)

**Comment by amareshdlphx** [comment]
Hi,
X-Ray report still showing alert on package: com.pivovarit:parallel-collectors. I guess X-Ray is using some metadata (pom) to identify the ownership may need refresh/update bom. 
Thanks.

**Comment by pivovarit** [comment]
> dig pivovarit.com

```
; <<>> DiG 9.10.6 <<>> pivovarit.com
;; AUTHORITY SECTION:
pivovarit.com.		1800	IN	SOA	dns.home.pl. admin.home.pl. 951139824 14400 7200 2419200 3600
```
