### ISSUE TITLE
Allow a creation of ParallelCollectors with dedicated Executors but without parallelism limit

### ISSUE THREAD

**Issue by ls-rein-martha** [pivovarit/parallel-collectors#918]
**Is your feature request related to a problem? Please describe.**
I want to set a dedicated custom executor of a virtual thread pool with proper naming without a limit of parallelism at `ParallelCollectors`

This is useful to see the proper thread name when I monitor my VT pinning.
- Even though I can see it from the stack trace of VT Pinning, it will be easier if I can group it based on my thread name
- It also less confusion in the analysis since currently, the default is blank thread name

**Describe the solution you'd like**
A static factory overloaded method to pass in the collector and the executor only (without parallelism count)

**Describe alternatives you've considered**
I set a high number of parallelisms at the parameter
It works, but it unnecessarily acquires semaphore in it.

**Additional context**
N/A

**Comment by pivovarit** [comment]
Hi! Thanks for the suggestion! If I understood you correctly, all you need is:
```
public static <T, R> Collector<T, ?, CompletableFuture<Stream<R>>> parallel(Function<T, R> mapper, Executor executor) {
    // ...
}
```

Which gives unlimited parallelism with a _null_ internal `Semaphore`?

**Comment by ls-rein-martha** [comment]
> Hi! Thanks for the suggestion! If I understood you correctly, all you need is:
> 
> ```
> public static <T, R> Collector<T, ?, CompletableFuture<Stream<R>>> parallel(Function<T, R> mapper, Executor executor) {
>     // ...
> }
> ```
> 
> Which gives unlimited parallelism with a _null_ internal `Semaphore`?

That is correct, thank you :)

**Comment by ls-rein-martha** [comment]
Not super important, another suggestion from my side is to have a supplier OR static-object to be configured as the `defaultExecutor`. But it probably will need some proper "config" API to make it nice for any future "configuration" purpose :)

Anyway, thank you again for the quick response and changes

**Comment by pivovarit** [comment]
Btw, feel free to toy with the code from my draft. I will probably merge it soon, but still wait some time, so that I can squeeze in more stuff into the next release
